public class RSI_UpdateLinkOnQuoteDocument{
    /*
    List<Id> storeQuoteDocumentIds = new List<Id>();
    public RSI_UpdateLinkOnQuoteDocument(List<SBQQ__QuoteDocument__c> quoteDocumentId) {
        for(SBQQ__QuoteDocument__c quoteDocument : quoteDocumentId) {
            storeQuoteDocumentIds.add(quoteDocument.Id);
        }
        //system.debug('Quote Document ID: '+storeQuoteDocumentIds);
        List<SBQQ__QuoteDocument__c> createdQuoteDocument = [SELECT Id, SBQQ__DocumentId__c, Document_Link__c FROM SBQQ__QuoteDocument__c WHERE
                                                             Id = :storeQuoteDocumentIds];
        
    }
    public void execute(QueueableContext context) {
    }
*/

}